### ISSUE TITLE
匿名比翻墙更重要

### ISSUE THREAD

**Issue by oilel** [hello-world-1989/temp#1]
翻墙只是能连接外网，但是匿名更重要。可以测试一下 https://github.com/oilel/pqt ，我的本地设备运行起来没问题，不确定能否跨平台连接。

**Comment by hello-world-1989** [comment]
> 翻墙只是能连接外网，但是匿名更重要。可以测试一下 https://github.com/oilel/pqt ，我的本地设备运行起来没问题，不确定能否跨平台连接。

已经更新

https://github.com/hello-world-1989/program-think-image
